---
- name: Notify via Slack
  slack:
    domain: "{{ slack_domain }}"
    channel: "{{ slack_channel }}"
    token: "{{ slack_token | mandatory }}"
    msg: "Playbook run against {{ project }}/{{ environment_tier }}"
  when: "not {{ slack_dry_run }}"
  tags:
    - slack
    - common

- name: Create ssh notification script
  template:
    src: ssh-notify.j2
    dest: "{{ slack_ssh_alert_path }}"
    owner: root
    group: staff
    mode: 0775
  when: slack_ssh_alert_enabled
  tags:
    - slack
    - monitoring
    - template-configuration
    - configuration

- name: Add notification to login hook
  lineinfile:
    dest: /etc/pam.d/sshd
    line: "session optional pam_exec.so seteuid {{ slack_ssh_alert_path }}"
  when: slack_ssh_alert_enabled
  tags:
    - slack
    - monitoring
    - template-configuration
    - configuration
